    console.log("RECETA TORTILLA DE PATATA\n")
    console.log("   Ingredientes\n")
    console.log("    Patatas..........700g")
    console.log("    Cebollas.........300g")
    console.log("    Huevos...........6")
    console.log("    Sal")
    console.log("    Aceite\n")
    console.log("COMO HACER TORTILLA DE PATATA\n")
    console.log("   Dificultad:media\n")
    console.log("    Tiempo............45m")
    console.log("    Elaboración.......30m")
    console.log("    Cocción...........15m\n")
    console.log("Caramelizar la cebolla: pelar, cortar en juliana y cocinar a fuego lento durante 30 minutos, removiendo ocasionalmente.\n")
    console.log("Freír las patatas lentamente en aceite casi frío para confitarlas, luego subir el fuego tras 10 minutos para dorarlas un poco y lograr contrastes.\n")
    console.log("Escurrir patatas y cebolla, mezclarlas con huevos batidos, cocinar la tortilla en sartén con aceite por 3-4 minutos y darle la vuelta. Sartenes dobles pueden facilitar esta operación.\n")
    console.log("La tortilla ya está lista!  (:\n")